# Generated by Django 4.2.10 on 2024-10-05 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_subscribe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
